### PR TITLE
Light theme

### PR DESCRIPTION
**Pull request by Jedd-Campbell**
1. Fixed reaction username contrast.
2. Fixed navbar account text color and dropdown list style.

I moved the navbar styling back to the global style sheet, as it wasn't taking precedence over the default styles while inside the component. 

image

### CODE REVIEW

**Comment by mtlynch** [comment]
I'd rather not add to the global style if we can avoid it. What do you think of just adding an ID field so that the navbar's CSS rules take precedence?

https://github.com/Jedd-Campbell/whatgotdone/pull/1

Also, not a big deal on this one, but in general it's helpful if there are [separate PRs for separate fixes](https://mtlynch.io/code-review-love/#5-narrowly-scope-changes). In this case, the reaction changes are an easy accept, but they're blocked due to unrelated discussion in the navbar component.

**Comment by Jedd-Campbell** [comment]
Good idea! I'll revert those changes and give it a swing.

Ah, sorry about that! In future I'll do more atomic PR's. 

I'll work on those in the next few hours. Thanks for your patience!

**Comment by mtlynch** [comment]
Oh, I made a PR into your branch with the fix:

https://github.com/Jedd-Campbell/whatgotdone/pull/1

You should be able to just accept that, and then I can merge this PR into master.

**Review by mtlynch — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
