### PR TITLE
Change to light UI theme

### PR DESCRIPTION
**Pull request by Jedd-Campbell**
Here's an alternative look and feel for WhatGotDone! 

- I kept it as noninvasive as possible (one css file, overriding existing styles).
- I kept the original colours.
- I kept the mobile responsiveness in mind.

This is my first PR to a public repo * ever *. It was tons of fun. No stress if you don't like it!

Screenshots:

_Landing page_
image

_Plain-text editor_
image

_Rich-text editor_
image

_Recent entries_
image

_Viewing an entry_
image

---
This change is [Reviewable](https://reviewable.io/reviews/mtlynch/whatgotdone/568)

### CODE REVIEW

**Review by mtlynch — CHANGES_REQUESTED** [review]
Nice, this looks really good! Thanks for making this.

There are only a few spots where I think it creates UI issues:







> *[Reviewable](https://reviewable.io/reviews/mtlynch/whatgotdone/568#-:-MYw8vRQ8Ua7aM0IVFEa:b2ec594)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Jedd-Campbell)

___
*[frontend/src/assets/css/light.css, line 68 at r1](https://reviewable.io/reviews/mtlynch/whatgotdone/568#-MYw9T4MAceiedB5uHKY:-MYw9T4MAceiedB5uHKZ:b-qjmjs5) ([raw file](https://github.com/mtlynch/whatgotdone/blob/1b7cb8b1d463baa7780cb39027e39689d6ff926b/frontend/src/assets/css/light.css#L68)):*
> ```CSS
> }
> 
> .feature {
> ```

For selectors that apply to multiple components, I think it makes sense to define them here, but for things like `.feature`, which is specific to Home.vue, could we keep the CSS in Home.vue? Otherwise, it becomes confusing to jump around between different CSS files figuring out which takes priority.

(ditto for `.contact-us`, `.reaction-buttons`, etc.)
___
*[frontend/src/assets/css/light.css, line 179 at r1](https://reviewable.io/reviews/mtlynch/whatgotdone/568#-MYw9mzl6V6wLydhk0G9:-MYw9mzl6V6wLydhk0GA:b-jws5sn) ([raw file](https://github.com/mtlynch/whatgotdone/blob/1b7cb8b1d463baa7780cb39027e39689d6ff926b/frontend/src/assets/css/light.css#L179)):*
> ```CSS
> 
> @media screen and (min-width: 768px) {
>   .jumbotron {
> ```

The convention I've been following is to keep media query selectors adjacent to their original selectors, like:

```css
.jumbotron { ... }

@media screen and (min-width: 768px) {
  .jumbotron { ... }
}

.jumbotron h1 { ... }

@media screen and (min-width: 768px) {
  .jumbotron h1 { ... }
}
```

**Comment by Jedd-Campbell** [comment]
Sure! I've been itching to give it a shot for a while now.

**Here's what I fixed:**

- [x] Contrast
- [x] Image borders
- [x] Larger menu font on smaller screens
- [x] CSS media query selections   

**CSS to specific components:**

Keeping it in one file will make it slightly easier to add themes at a later stage. I'd like to try my hand at a dark theme, and a code theme, and would be willing to add the theme switching. 

For now though, should I:
a. Move specific CSS to components as suggested?
b. Keep the CSS file as is?
c. Split the CSS file into two (main.css and light.css) where the light.css file styles the colors, and the main.css styles all the rest?

Thanks for the review :)

**Review by mtlynch — COMMENTED** [review]
> Keeping it in one file will make it slightly easier to add themes at a later stage. I'd like to try my hand at a dark theme, and a code theme, and would be willing to add the theme switching.

Oh, good question! I'm not really sure of best practices around theming, as I've never had an app with configurable themes.

One solution that comes to mind is to use theme files to define variables and then the components reference those variables. You can see an example of this in TinyPilot:

https://github.com/mtlynch/tinypilot/blob/679c5e89cc4bd048ab4a8daee5a2be2204c40e24/app/static/css/style.css

Ideally the theme would be general and wouldn't know about particulars of different components. It should define things that the components use to inform their own layout without referencing them directly.

> *[Reviewable](https://reviewable.io/reviews/mtlynch/whatgotdone/568#-:-MZ-N902-3RmlhaNgIpF:b-o5www9)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Jedd-Campbell)

**Comment by Jedd-Campbell** [comment]
I'm not too sure either. I haven't done a themed app myself. Your suggestion with separate theme files makes a ton of sense. 

I moved the component-specific CSS to their relevant components. It shouldn't be too difficult to refactor when tackling themes, so I opted to keep to your convention for now.

**Review by mtlynch — APPROVED** [review]
:lgtm: 

Thanks!

> *[Reviewable](https://reviewable.io/reviews/mtlynch/whatgotdone/568#-:-MZKktXd7d4UuVKvEJkd:b-41s8zb)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @Jedd-Campbell)

**Pull request merged**
