### PR TITLE
Check for existing keys when appending entries to store.recentEntries

### PR DESCRIPTION
**Pull request by smartrack**
Appending to recentEntries store only if the new entry key is unique

---
This change is [Reviewable](https://reviewable.io/reviews/mtlynch/whatgotdone/449)

### CODE REVIEW

**Comment by mtlynch** [comment]
Thanks @smartrack.

This seems to have pulled in your old changes as well as your new changes. Could you [rebase](https://www.freecodecamp.org/news/an-introduction-to-git-merge-and-rebase-what-they-are-and-how-to-use-them-131b863785f/) onto mtlynch:master to create a clean PR?

**Comment by mtlynch** [comment]
Oh, you don't need to close it. If you force push (`git push [remote] [branch] -f`) after a rebase, it fixes the issue in your PR. But a new PR works too.

**Comment by smartrack** [comment]
I did rebase and re-opened PR

**Comment by smartrack** [comment]
Removed dead code and optimized key lookup to prevent duplicate entry

**Comment by mtlynch** [comment]
LGTM, thanks!

**Pull request merged**
