### PR TITLE
Static Router Change

### PR DESCRIPTION
**Pull request by GrimTheReaper**
Resolves https://github.com/mtlynch/whatgotdone/issues/292

Functionally I don't believe this changes much, other than the readability of the code and by auto discovering files as opposed to having them written out in the backend. A few other changes I plan on discussing are changing how the application runs and is configured. Things like `./frontend/dist` should not be hardcoded, and realistically, the frontend should actually be in a separate repo from the backend. 

NOTE:
Didn't get a chance to test this in your code, but I pulled it out and tested it elsewhere. I'm having gcp issues today 😢

---
This change is [Reviewable](https://reviewable.io/reviews/mtlynch/whatgotdone/297)

### CODE REVIEW

**Comment by GrimTheReaper** [comment]
Yeah I can do that when I get back to my computer tonight 😄

**Comment by GrimTheReaper** [comment]
So, I somehow missed that you were using templating 😅 
It might take me a bit longer but I'm working on fixing my PR, and I'll let you know when I get it working.

**Comment by GrimTheReaper** [comment]
> Ideally, these separate concerns would be in separate PRs.

I altered the PR to only contain the Static Router Change, and will break down the other changes I'll like to make into issues and future PRs.

---

> My current convention is to use present tense rather than future tense (ditto throughout)

Changed to accommodate.

---

> Why the double http.Dir calls?

I didn't see that, my bad.

---

> Can we handle the err != nil case?

Good catch, I didn't see that. Fixed to actually check all errors.

---

> The current PR breaks functionality. When applied, requests to / return a 0-length response. It will be easier to debug it if we reduce it to just item (1).

I did more testing, and apparently `http.FileSystem` does not complain if the file exists but is also a directory, even though it can't exactly open/serve it. I added more checks that should actually catch that case.

**Comment by mtlynch** [comment]
LGTM, thanks @GrimTheReaper.

**Comment by GrimTheReaper** [comment]
You did at least test it right? While I tested the functionality of the static handler, I didn't test it while inside of the application given I'm still experiencing GCP issues.

**Comment by mtlynch** [comment]
Yep, I tested it. It's deployed to production now (I just had to fix some unit tests):

https://circleci.com/gh/mtlynch/whatgotdone/1799

**Pull request merged**
